import omnifoodImg from '@/public/images/projects/omnifood.png';
// import guessImg from '@/public/images/projects/guess.png';
import splitterImg from '@/public/images/projects/splitter.png';
import devfinderImg from '@/public/images/projects/devfinder.png';
import pizzaImg from '@/public/images/projects/pizzaApp.png';
import quizImg from '@/public/images/projects/quiz.png';
import todoappImg from '@/public/images/projects/todoapp.png';
import bitsbobsImg from '@/public/images/projects/bitsbobs.png';
import expensetrackerImg from '@/public/images/projects/expensetracker.png';
import proshopImg from '@/public/images/projects/proshop-product.png';
import portfolioV1Img from '@/public/images/projects/portfolioV1.png';
// import elMiradorImg from '@/public/images/projects/el-mirador.png';

const projectsData = [
  {
    id: 7,
    urlName: 'quiz-app',
    // imageURL: '../../../img/quiz.png ',
    imageURL: quizImg,
    title: 'Quiz',
    summary: 'React quiz with 15 questions to test your knowledge !',
    desc: 'React quiz with 15 questions to test your knowledge ! Features include a timer, a cancel/exit button, a highscore and a restart button. Deployed on Netlify, later on Vercel just to test things out with a server and practice Express.',
    tech: ['React', 'Context API', 'Express', 'Vercel'],
    other: '',
    demoURL: 'https://react-quiz-6l23.vercel.app/',
    codeURL: 'https://github.com/alicefrsr/react-quiz',
    categories: ['React', 'Full Stack'],
  },
  {
    id: 8,
    urlName: 'pizza-app',
    // imageURL: '../../../img/pizzaApp.png ',
    imageURL: pizzaImg,
    title: "Chiara's Pizza Place",
    summary: 'Order your pizzas here !',
    desc: "Order your pizzas here and pay on delivery! Add and remove pizzas to/from your cart, use geolocation to input address for delivery, search for orders. We'll tell you how long you have to wait and if you are really  hungry, you can set your order to priority, we'll speed up that order for you! ",
    tech: [
      'React',
      'React Router',
      'Redux Toolkit',
      'Tailwind',
      'Responsive',
      'Supabase',
    ],
    other: '',
    demoURL: 'https://chiaras-pizza.netlify.app/',
    codeURL: 'https://github.com/alicefrsr/react-router-pizza',
    categories: ['React', 'Full Stack', 'Responsive'],
  },
  {
    id: 6,
    urlName: 'bits-and-bobs',
    // imageURL: '../../../img/bitsbobs.png',
    imageURL: bitsbobsImg,
    title: 'Bits & Bobs',
    summary:
      'Personal learning website I used to gather components and mini-apps while exploring how React works.',
    desc: 'Personal learning website I put together to gather all my React experiments in one place so I could have them as a reference.',
    tech: [
      'React',
      'Custom hooks',
      'useReducer',
      'React Router',
      'CSS Modules',
      'Redux',
      'RESTful APIs',
    ],
    other: '',
    demoURL: 'https://bits-and-bobs.netlify.app/',
    codeURL: 'https://github.com/alicefrsr/react-bits-and-bobs',
    categories: ['React'],
  },

  {
    id: 3,
    urlName: 'splitter',
    // imageURL: '../../../img/splitter.png ',
    imageURL: splitterImg,
    title: 'Splitter',
    summary: 'Tip calculator / bill splitter app.',
    desc: 'Tip calculator / bill splitter app. The focus was on learning Javascript, CSS Flexbox and web accessibility. Frontend Mentor challenge, with CSS changes for accessibility.',
    tech: ['HTML', 'Responsive', 'Vanilla JS', 'Web accessibility'],
    other: '',
    demoURL: 'https://splitter-demo.netlify.app/',
    codeURL: 'https://github.com/alicefrsr/Splitter',
    categories: ['Vanilla JS', 'HTML/CSS Integration', 'Responsive'],
  },
  {
    id: 4,
    urlName: 'devfinder',
    // imageURL: '../../../img/devfinder.png',
    imageURL: devfinderImg,
    title: 'Devfinder',
    summary:
      'A simple React app to search for Github users information using the Github API.',
    desc: 'A simple React app to search for Github users information using the Github API. A Frontend Mentor challenge to practice CSS, flexbox, implement dark/light mode using the Context API.',
    tech: ['React', 'Context API', 'Responsive', 'Github API'],
    other: '',
    demoURL: 'https://devfinder-demo.netlify.app/',
    codeURL: 'https://github.com/alicefrsr/React-devfinder-App',
    categories: ['React', 'HTML/CSS Integration', 'Responsive'],
  },
  // {
  //   id: 5,
  //   urlName: 'todo-app',
  //   // imageURL: '../../../img/todoapp.png ',
  //   imageURL: todoappImg,
  //   title: 'Things to do',
  //   summary: 'Another to-do app...',
  //   desc: 'Add, edit, delete your todos, saved to local storage. I used the same project to learn about the Context API, useReducer, how to implement customs hooks.',
  //   tech: ['React', 'Context API', 'useReducer', 'Custom hooks'],
  //   other: '',
  //   demoURL: 'https://another-todoapp.netlify.app/',
  //   codeURL: 'https://github.com/alicefrsr/React-todoApp',
  //   categories: ['React'],
  // },
  // {
  //   id: 1,
  //   urlName: 'Omnifood',
  //   // imageURL: '../assets/images/projects/omnifood.png',
  //   imageURL: omnifoodImg,
  //   title: 'Omnifood',
  //   summary: 'Static website showcasing a fictitious food delivery company.',
  //   desc: 'Static website showcasing a fictitious food delivery company. One of my first projects  to learn CSS and responsive design.',
  //   tech: ['HTML', 'Responsive', 'Vanilla JS'],
  //   other: '',
  //   demoURL: 'https://food-ai-demo.netlify.app/',
  //   codeURL: 'https://github.com/alicefrsr/Omnifood',
  //   categories: ['HTML/CSS Integration', 'Responsive'],
  // },
  // {
  //   id: 2,
  //   urlName: 'guessing-game',
  //   // imageURL: '../../../img/guess.png',
  //   imageURL: guessImg,
  //   title: 'Guessing game',
  //   summary: 'Guess The Number game, retro style.',
  //   desc: 'Guess The Number game, retro style. Try to guess a random number between 1 and 100 in as little rounds as possible and save your score. One of my first projects while learning basic logic with Javascript.',
  //   tech: ['HTML', 'CSS', 'Vanilla JS'],
  //   other: '',
  //   demoURL: 'https://guessing-game-demo.netlify.app/',
  //   codeURL: 'https://github.com/alicefrsr/GuessTheNumber',
  //   categories: ['Vanilla JS'],
  // },

  {
    id: 9,
    urlName: 'expensetracker-app',
    // imageURL: '../../../img/expensetracker.png',
    imageURL: expensetrackerImg,
    title: 'Expensetracker',
    summary:
      'Simple budget app to add and delete income and expenses, using the MERN stack.',
    desc: "Simple budget App to add and delete income and expenses, using the MERN stack. (Deployed on render.com's free plan, please allow 30sec for project to load!)",
    tech: [
      'React',
      'Responsive',
      'Node.js',
      'Rest API',
      'Postman',
      'Express',
      'MongoDB',
    ],
    other: '',
    demoURL: 'https://expense-tracker-app-9kw2.onrender.com',
    codeURL: 'https://github.com/alicefrsr/React-expense-tracker-App',
    categories: ['React', 'Full Stack', 'Responsive'],
  },
  {
    id: 10,
    urlName: 'e-commerce',
    // imageURL: '../../../img/proshop-product.png',
    imageURL: proshopImg,
    title: 'e-commerce',
    summary:
      "Fullstack e-commerce platform, following Brad Traversy's Udemy tutorial,",
    desc: "Fullstack e-commerce platform, following Brad Traversy's Udemy tutorial, to further consolidate my Redux skills and all CRUD operations on a database. A good exposure to authentification with JWT, PayPal & Credit card integration. (Deployed on render.com's free plan, please allow 30sec for project to load!)",
    tech: [
      'React',
      'Bootstrap',
      'Redux',
      'JWT Tokens',
      'Node.js',
      'Rest API',
      'Postman',
      'Express',
      'MongoDB',
    ],
    other: '',
    demoURL: 'https://e-commerce-demo-proshop.onrender.com',
    codeURL: 'https://github.com/alicefrsr/e-commerce-demo',
    categories: ['React', 'Full Stack'],
  },
  // {
  //   id: 11,
  //   urlName: 'el-mirador',
  //   // imageURL: '../../../img/el-mirador.png',
  //   imageURL: elMiradorImg,
  //   title: 'El Mirador',
  //   desc: 'Landing page for a local restaurant in Aragon, Spain. Client requested a simple static page to have an online presence other than just Google reviews. Hosted on Hostinger using Github  repo for auto-deployment. Focus on SEO.',
  //   tech: ['HTML', 'Responsive CSS', 'Hostinger', 'Github'],
  //   other: '',
  //   demoURL: 'Coming soon!',
  //   codeURL: 'Private repo for now, coming soon!',
  //   categories: ['Professional'],
  // },
  {
    id: 101,
    urlName: 'first-portfolio',
    // imageURL: '../../../img/proshop-product.png',
    imageURL: portfolioV1Img,
    title: 'Portfolio v1.0',
    summary: 'My first portfolio built using React. ',
    desc: 'My first portfolio built using React, showcasing earlier projects from CSS integration exercises to Vanilla JS games. The objective was to be able to filter according to project categories and implement accessibles modals.',
    tech: ['React', 'Tailwind', 'Custom hooks'],
    other: '',
    demoURL: 'https://huggabug.netlify.app/',
    codeURL: 'https://github.com/alicefrsr/react-tw-portfolio',
    categories: ['React'],
  },
] as const;

export default projectsData;
